FROM node:24-alpine
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
EXPOSE 3000
ENV WATCHPACK_POLLING=true    
ENV CHOKIDAR_USEPOLLING=true
CMD ["npm", "run", "dev", "--", "-H", "0.0.0.0"]